directories:
  output: release/${version}
  buildResources: build
appId: com.meetinghelper.app
productName: Meeting Helper
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
mac:
  icon: build/icon.icns
  target:
    - target: dmg
      arch:
        - x64
        - arm64
win:
  icon: build/icon.ico
linux:
  icon: build/icon.png
electronVersion: 25.9.8
